apiVersion: v1
kind: Service
metadata:
  name: edge-api-server
  namespace: kube-system
  labels:
    app: edge-api-server
spec:
  type: ClusterIP
  ports:
  - port: 443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: edge-api-server
