apiVersion: apps/v1
kind: Deployment
metadata:
  name: edge-ui
  labels:
    app: edge-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge-ui
  template:
    metadata:
      labels:
        app: edge-ui
    spec:
      containers:
      - name: edge-ui
        image: rancher/edge-ui:latest
        env:
        - name: API
          value: "https://edge-api-server.kube-system:443"
        ports:
        - containerPort: 80
          protocol: TCP
